config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :venues do
    resources :reviews
  end
end

app/models/accessibility_feature.rb
class AccessibilityFeature < ApplicationRecord
  has_many :venue_features
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :venue
  belongs_to :user
  has_many_attached :photos
end

app/models/saved_venue.rb
class SavedVenue < ApplicationRecord
  has_many :users
  has_many :venues
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_one_attached :photo
  has_many :venues, through: :saved_venues
end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :venue_category
  has_many :reviews, dependent: :destroy
  has_many :venue_features
  has_many :accessibility_features, through: :venue_features
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many_attached :photos
  belongs_to :saved_venues
end

app/models/venue_category.rb
class VenueCategory < ApplicationRecord
  has_many :venues
end

app/models/venue_feature.rb
class VenueFeature < ApplicationRecord
  belongs_to :venue
  belongs_to :accessibility_feature
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_venue, only: %i[new create]

  def new
    @venue = Venue.find(params[:venue_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.venue = @venue
    @review.user = current_user
    @review.save
    redirect_to venue_path(@venue)
  end

  private

  def set_venue
    @venue = Venue.find(params[:venue_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating, :photos)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = current_user
    end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @accessibility_features = AccessibilityFeature.all
    @venues = []

    @accessibility_features.each do |feature|
      venue_filter(feature.feature) if params["feature#{feature.id}"]
    end

    @venues = Venue.all if @venues.empty?

    ## hey
    @markers = @venues.map do |venue|
      {
        lat: venue.latitude,
        lng: venue.longitude,
        info_window: render_to_string(partial: "info_window", locals: { venue: venue }),
        image_url: helpers.asset_url("custom-map-marker.png")
      }
    end
  end

  def show
    @venue = Venue.find(params[:id])
    @saved_venues = SavedVenue.where(user_id: current_user)
  end

  def venue_filter(feature_name)
    venue_features = VenueFeature.accessibility_feature_search(feature_name)
    venue_features.each do |feature|
      @venues << feature.venue
    end
  end
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#0081a7">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#0081a7">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#0081a7">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adept</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'application/favicon' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="h-100">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- Banner -->
<div class="banner">
  <div class="intro">
    <h2>A community driven solution for an inclusive future</h2>
    <form action="#">
      <label for="search" style="color: #fff; font-weight: lighter;">Find places nearby</label>
      <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Type postcode or address..." aria-label="Type postcode or address" aria-describedby="search">
        <button class="input-group-text adept-btn small" id="search">
          <i class="fa-solid fa-magnifying-glass"></i>
        </button>
     </div>
    </form>
  </div>
</div>
<!-- What is adept -->
<div class="container">
  <div class="row">
    <div class="col-md-4 what-is-adept" id="what">
        <h3>What is adept?</h3>
        <p>Adept is a community driven solution that allows you to find and filter venues to your accessibility needs</p>
        <%= image_tag('magnifier.png', alt: "An image of a magnifier") %>
        <%= link_to "Learn more", nil, class: "adept-btn large" %>
    </div>
    <div class="col-md-4 what-is-adept" id="find">
        <h3>Find, visit and enjoy!</h3>
        <p>Find a place that fits your accesibility requirements, visit and have a blast with friends and family</p>
        <%= image_tag('beer.png', alt: "An image of beer and celebration") %>
        <%= link_to "Find place", venues_path, class: "adept-btn large" %>
    </div>
    <div class="col-md-4 what-is-adept" id="review">
        <h3>Review and share!</h3>
        <p>Adept is a community driven solution that allows you to find and filter venues to your accessibility needs </p>
        <%= image_tag('star.png', alt: "An image of a star. Rate you favourite places!") %>
        <%= link_to "Review place", nil, class: "adept-btn large" %>
    </div>
  </div>
</div>
<!-- What others say -->
<div class="container-fluid" style="background-color: rgba(0, 129, 167, .1);">
  <div class="row">
    <div class="what-others-say col-offset-md-12 text-center">
      <h3>What do others think?</h3>
      <div class="comment">
        <%= link_to ("https://www.tagesspiegel.de/") do %>
          <%= image_tag('tagesspiegel_logo.png', width: 250, alt: "Tagesspiegel logo") %>
        <% end %>
        <p>Nostra eu nunc eu ante aliquam dictumst nisl a parturient at a a praesent nisl praesent nullam nisl.</p>
        <small>- Frank Müller - Chief Editor</small>
      </div>
      <div class="comment">
        <%= link_to ("https://www.telegraph.co.uk/") do %>
          <%= image_tag('telegraph_logo.png', width: 250, alt: "The Telegraph logo") %>
        <% end %>
        <p>Eget aptent euismod a luctus parturient ridiculus vestibulum nisi consectetur adipiscing.</p>
        <small>- Jane Doe - IT Editor</small>
      </div>
    </div>
  </div>
</div>

app/views/pages/my-profile.html.erb
<div class="cover">
  <div>
    <h1>My Profile</h1>
  </div>
</div>
<% flash.now[:notice] = params[:flash_notice] if params[:flash_notice] %>
<div class="text-container mt-4 mb-4">
  <div><h3>My venues</h3></div>
  <div class="row">
    <div class="col index-col">
      <% @venues.each do |venue| %>
        <%= link_to venue_path(venue), class:"link" do %>
          <div class="venue-card">
              <%= cl_image_tag venue.photo.key, height: 400, width: 400, class: 'card-img-top', crop: :fill %>
            <div class="card-body">
              <div class="venue-description name">
                <%= venue.name %>
              </div>
            </div>
            <div class="card-footer">
              <%= venue.address %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container py-5 px-4">
  <div class="d-flex justify-content-between align-items-center">
      <%= link_to :back do %>
        <i class="fa-solid fa-fw fa-arrow-left"></i> Back
      <% end %>
    <h2><%= @venue.name %></h2>
    <div></div>
  </div>
  <div class="py-3">
    <%= simple_form_for [@venue, @review] do |f| %>
      <%= f.input :content, as: :text %>
      <%= f.input :rating, collection: 1..5, selected: 5 %>
      <%= f.input :photos, as: :file %>
      <%= f.submit "Submit review", class: "btn adept-btn text-center" %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="d-flex justify-content-center py-3">
      <!-- Instagram -->
      <%= link_to ("https://www.instagram.com"),
          class: "btn btn-link btn-floating btn-lg text-white m-1",
          aria: { label: "Checkout our Instagram account" } do %>
        <i class="fab fa-instagram"></i>
      <% end %>

      <!-- Github -->
      <%= link_to ("https://github.com/henderson907/adept"),
           class: "btn btn-link btn-floating btn-lg text-white m-1",
           aria: { label: "Checkout our Github account" } do %>
        <i class="fab fa-github"></i>
      <% end %>

      <!-- Facebook -->
      <%= link_to ("https://www.facebook.com"),
          class: "btn btn-link btn-floating btn-lg text-white m-1",
          aria: { label: "Checkout our Facebook account!" } do %>
        <i class="fab fa-facebook-f"></i>
      <% end %>
</footer>

app/views/shared/_form-sign-up.html.erb
<div class="form-sign-up-container d-flex">
        <%= simple_form_for(@user) do |f| %>
        <div class="form-user-box">
<h2><%= "Add a mighty user!"%></h2>
            <%= f.input :name %>
            <%= f.input :email %>
            <%= f.input :encrypted_password,
              validates :encrypted_password, :presence => true,
                       :confirmation => true,
                       :length => {:within => 6..40},
                       :on => :create
            validates :encrypted_password, :confirmation => true,
                       :length => {:within => 6..40},
                       :allow_blank => true,
                       :on => :update
                       %>
            <%= f.input :encrypted_password_confirmation ,
            <%= f.input :photo, as: :file %>
            <%= f.submit class: 'btn btn-primary'  %>
        </div>
        <% end %>
</div>

app/views/shared/_form.html.erb
<div class="form-venue-container d-flex">
        <%= simple_form_for(@venue) do |f| %>
        <div class="form-venue-box">
<h2><%= "Add a venue!"%></h2>
            <%= f.input :name %>
            <%= f.input :phone %>
            <%= f.input :category, as: :select, collection: [['Hot','hot'],['Medium','medium'],['Cold','cold']], prompt: 'Select category' %>
            <%= f.input :website %>
            <%= f.input :hours %>
            <%= f.input :address,
                        input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
                        wrapper_html: {data: {controller: "address-autocomplete",
                        address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
            %>
            <%= f.input :photo, as: :file %>
            <%= f.submit class: 'btn btn-primary'  %>
        </div>
        <% end %>
    <img class="img-display" src="https://images.freeimages.com/images/premium/previews/3329/33294946-rome-pin-map.jpg" alt="Card image cap">
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-adept">
  <div class="container-fluid">
    <%= link_to(raw("<h1>Adept</h1>"), root_path, class: "navbar-brand", aria: { label: "Adept logo. Returns to home" }) %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-fw fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" aria-label="Options">
        <li class="nav-item">
          <%= link_to (root_path), class: "nav-link d-flex justify-content-between align-items-center" do %>
            Home
            <i class="fa-solid fa-arrow-right fa-fw d-lg-none"></i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to (venues_path), class: "nav-link d-flex justify-content-between align-items-center" do %>
            Venues
            <i class="fa-solid fa-arrow-right fa-fw d-lg-none"></i>
          <% end %>
        </li>
        <li class="nav-item line-separator">
          <%= link_to (nil), class: "nav-link d-flex justify-content-between align-items-center" do %>
            About Us
            <i class="fa-solid fa-arrow-right fa-fw d-lg-none"></i>
          <% end %>
        </li>
      </ul>
      <ul class="navbar-nav mb-2 mb-lg-0" aria-label="User settings">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to (nil), class: "nav-link" do %>
              <i class="fa-solid fa-user fa-fw d-lg-none d-inline-block"></i>My profile
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to (destroy_user_session_path), class: "nav-link", data: { turbo_method: :delete } do %>
              <i class="fa-solid fa-sign-out fa-fw d-lg-none d-inline-block"></i>Logout
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to (new_user_session_path), class: "nav-link" do %>
              <i class="fa-solid fa-sign-in fa-fw d-lg-none d-inline-block"></i>Login
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to (new_user_registration_path), class: "nav-link" do %>
              <i class="fa-solid fa-user-plus fa-fw d-lg-none d-inline-block"></i>Sign up
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/venues/_form.html.erb
<%= f.input :address,
  input_html: {data: {"..."}, class: "d-none"},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

app/views/venues/_info_window.html.erb
<h2><%= venue.name %></h2>
<%= link_to "More Details", venue_path(venue) %>

app/views/venues/index.html.erb
<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

app/views/venues/new.html.erb
<div class="container py-5">
      <%= render "shared/form"  %> 
</div>

app/views/venues/show.html.erb
<% content_for :meta_title, "Adept | #{@venue.name}" %>
<div class="venue-banner">
  <% if @venue.photos.count > 0 %>
   <%= cl_image_tag @venue.photos.first.key, :quality => "auto", :fetch_format=>:auto %>
  <% end %>
</div>

<div class="container py-5 px-4">
  <!-- Main-->
  <h3><%= @venue.name %></h3>
  <p><%= @venue.venue_category.category %></p>
  <div class="d-flex justify-content-between align-items-top my-4">
      <% if @venue.reviews.count == 0 %>
        No reviews yet
     <% else %>
        <div>
          <i class="fa-solid fa-star fa-fw" style="color: #F8BD45;"></i>
          <%= pluralize(@venue.reviews.count, 'review') %>
        </div>
     <% end %>
      <%= link_to new_venue_review_path(@venue) do %>
        <i class="fa-solid fa-pencil"></i> Add review
      <% end %>
      <%= link_to (nil) do %>
        <% if @saved_venues.empty? %>
          <i class="fa-regular fa-heart"></i> Save
        <% else %>
          <i class="fa-solid fa-heart"></i> Saved
        <% end %>
      <% end %>
  </div>
  <!-- Category / Address -->
  <div class="location my-4">
    <p><i class="fa-solid fa-fw fa-location-dot"></i> <%= @venue.address %></p>
  </div>
  <div class="features my-5">
      <% @venue.accessibility_features.sort_by(&:feature).each do |feature| %>
        <span class="bubble"><%= feature.feature %></span>
      <% end %>
  </div>
  <!-- Reviews -->
  <div class="reviews my-5">
    <h5>Reviews</h5>
    <% if @venue.reviews.count == 0 %>
      <p>No reviews yet</p>
    <% else %>
      <% @venue.reviews.sort_by(&:created_at).reverse.each do |review| %>
        <div class="review">
          <p><em><%= review.user.first_name %> <%= review.user.last_name %></em></p>
          <p><%= review.content %></p>
          <p>
            <% for i in 1..review.rating %>
                <i class="fa-solid fa-star fa-fw" style="color: #F8BD45;"></i>
              <% end %>
          </p>
          <small class="text-right"><%= review.created_at.strftime('%d/%m/%Y - %H:%M') %></small>
        </div>
      <% end %>
    <% end %>
  </div>
  <!-- Back -->
  <%= link_to :back do %>
    <i class="fa-solid fa-fw fa-arrow-left"></i> Back
  <% end %>
</div>